### ISSUE TITLE
Docs page did not deploy

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lcls-twincat-motion-example#2]
Need to investigate and fix

**Comment by klauer** [comment]
https://github.com/pcdshub/lcls-twincat-motion-example/tree/gh-pages ?

**Comment by ZLLentz** [comment]
https://pcdshub.github.io/lcls-twincat-motion-example is a 404 and in the last travis: https://travis-ci.org/github/pcdshub/lcls-twincat-motion-example/jobs/680761877#L314

Perhaps my lazy direct typo fix messed something up

**Comment by ZLLentz** [comment]
![image](https://user-images.githubusercontent.com/10647860/80541448-04494d80-8960-11ea-8198-c9bae57d9b60.png)

**Comment by ZLLentz** [comment]
It deployed now, closing.
